### PR TITLE
issue #6 - adding initial tests

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
Started some tests for the wsdl2rest extension. Ran into some weird issues trying to mock the file open step of the extension... https://github.com/bfitzpat/vscode-wsdl2rest/pull/7 Any ideas @lhein or @apupier ?

**Comment by lhein** [comment]
What problems did u face? What are you trying to achieve?

**Comment by bfitzpat** [comment]
```
brianf@brianf-work MINGW64 ~/Documents/GitHub/vscode-wsdl2rest (issue6-add-initial-tests)
$ npm test

> vscode-wsdl2rest@0.0.1 test c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> npm run vscode:prepublish && node ./node_modules/vscode/bin/test


> vscode-wsdl2rest@0.0.1 vscode:prepublish c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> npm run clean && npm run fatjar && npm install && npm run compile


> vscode-wsdl2rest@0.0.1 clean c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> rm -rf out || rmdir out /s /q


> vscode-wsdl2rest@0.0.1 fatjar c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> mvn install -f ./wsdl2rest/pom.xml

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Wsdl2Rest Fat Jar 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ wsdl2rest-fatjar ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.\wsdl2rest\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ wsdl2rest-fatjar ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ wsdl2rest-fatjar ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.\wsdl2rest\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ wsdl2rest-fatjar ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ wsdl2rest-fatjar ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ wsdl2rest-fatjar ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO]
[INFO] --- spring-boot-maven-plugin:2.1.0.RELEASE:repackage (default) @ wsdl2rest-fatjar ---
[INFO] Replacing main artifact c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.\wsdl2rest\target\wsdl2rest-fatjar-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ wsdl2rest-fatjar ---
[INFO] Installing c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.\wsdl2rest\target\wsdl2rest-fatjar-0.0.1-SNAPSHOT.jar to C:\Users\brianf\.m2\repository\org\github\camel\tooling\wsdl2rest\wsdl2rest-fatjar\0.0.1-SNAPSHOT\wsdl2rest-fatjar-0.0.1-SNAPSHOT.jar
[INFO] Installing c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.\wsdl2rest\pom.xml to C:\Users\brianf\.m2\repository\org\github\camel\tooling\wsdl2rest\wsdl2rest-fatjar\0.0.1-SNAPSHOT\wsdl2rest-fatjar-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.541 s
[INFO] Finished at: 2019-02-20T07:07:08-07:00
[INFO] Final Memory: 22M/309M
[INFO] ------------------------------------------------------------------------

> vscode-wsdl2rest@0.0.1 preinstall c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> node ./scripts/preinstall.js

wsdl2rest\config\logging.properties copied.
wsdl2rest\target\wsdl2rest-fatjar-0.0.1-SNAPSHOT.jar copied.

> vscode-wsdl2rest@0.0.1 postinstall c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.29.1
Found minimal version that qualifies engine range: 1.29.1
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/bc24f98b5f70467bc689abf41cc5550ca637088e/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

npm WARN vscode-wsdl2rest@0.0.1 No repository field.
npm WARN vscode-wsdl2rest@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 7645 packages in 7.671s
found 0 vulnerabilities


> vscode-wsdl2rest@0.0.1 compile c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
Running extension tests: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.vscode-test\stable\Code.exe c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test --extensionDevelopmentPath=c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest --extensionTestsPath=c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test --locale=en


[main 2019-02-20T14:07:22.260Z] update#setState idle

Rejected cached data from file: C:\Users\brianf\AppData\Roaming\Code\CachedData\7c66f58312b48ed8ca4e387ebd9ffe9605332caa\wsdl_file.test-69783e1b70c4b0dc1f3a93ccfebcadd6.code

Rejected cached data from file: C:\Users\brianf\AppData\Roaming\Code\CachedData\7c66f58312b48ed8ca4e387ebd9ffe9605332caa\app_soap-d8d5f2f5695c6b5d1ad329731ca10182.code
Rejected cached data from file: C:\Users\brianf\AppData\Roaming\Code\CachedData\7c66f58312b48ed8ca4e387ebd9ffe9605332caa\wsdl_url.test-bb0f91e2f062755d0ad2175409988ba4.code



  ensure Wsdl2rest extension exists and is accessible

    √ Extension should be present

    √ should activate (100ms)

    √ should register all wsdl2rest commands


  Wsdl2rest Extension Tests from wsdl file

addressWsdlPath = c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\src\test\address.wsdl

addressWsdlUri = file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl
[DEBUG] WSDL File URI: file:///c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl
[DEBUG] DSL Type: Spring
[DEBUG] Ouput Folder: src/main/java
[DEBUG] JAXWS Endpoint: http://localhost:8080/somepath
[DEBUG] JAXRS Endpoint: http://localhost:8081/jaxrs

[DEBUG] New config folder: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\config

[DEBUG] Log4J Config: file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/out/test/config/logging.properties
[DEBUG] Java Binary: C:\Program Files\Java\jdk1.8.0_162\bin\java
[DEBUG] Wsdl2Rest JAR: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\jars\wsdl2rest.jar
[DEBUG] Java Call: C:\Program Files\Java\jdk1.8.0_162\bin\java
        -Dlog4j.configuration=file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/out/test/config/logging.properties,-jar,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\jars\wsdl2rest.jar,--wsdl,file:///c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl,--out,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\src\main,--camel-context,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\src\main\resources\META-INF\spring\camel-context.xml,--jaxrs,http://localhost:8081/jaxrs,--jaxws,http://localhost:8080/somepath

[DEBUG] Retrieving document at 'file:/c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl'.


[DEBUG] Services:


[DEBUG]         AddressService

[DEBUG]         Port: AddressPort

[DEBUG]         Binding: Address

[DEBUG]         PortType: Address


[DEBUG]         Operations:


[DEBUG]                 Operation: delAddress


[DEBUG]                         Input:


[DEBUG]                         Message: delAddress


[DEBUG]                         Part: :delAddress


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.DelAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}delAddress


[DEBUG]                         Output:


[DEBUG]                         Message: delAddressResponse


[DEBUG]                         Part: :delAddressResponse


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.DelAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}delAddressResponse

[DEBUG]                         Faults:


[DEBUG]                 Operation: addAddress


[DEBUG]                         Input:


[DEBUG]                         Message: addAddress


[DEBUG]                         Part: :addAddress


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.AddAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}addAddress


[DEBUG]                         Output:


[DEBUG]                         Message: addAddressResponse


[DEBUG]                         Part: :addAddressResponse


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.AddAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}addAddressResponse

[DEBUG]                         Faults:


[DEBUG]                 Operation: listAddresses


[DEBUG]                         Input:
                        Message: listAddresses


[DEBUG]                         Part: :listAddresses
                                Params: org.jboss.fuse.wsdl2rest.test.doclit.ListAddresses {http://doclit.test.wsdl2rest.fuse.jboss.org/}listAddresses


[DEBUG]                         Output:
                        Message: listAddressesResponse


[DEBUG]                         Part: :listAddressesResponse


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.ListAddressesResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}listAddressesResponse


[DEBUG]                         Faults:

[DEBUG]                 Operation: updAddress

[DEBUG]                         Input:


[DEBUG]                         Message: updAddress


[DEBUG]                         Part: :updAddress


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.UpdAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}updAddress


[DEBUG]                         Output:

[DEBUG]                         Message: updAddressResponse


[DEBUG]                         Part: :updAddressResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.UpdAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}updAddressResponse
[DEBUG]                         Faults:


[DEBUG]                 Operation: getAddress

[DEBUG]                         Input:

[DEBUG]                         Message: getAddress

[DEBUG]                         Part: :getAddress


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.GetAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}getAddress

[DEBUG]                         Output:


[DEBUG]                         Message: getAddressResponse

[DEBUG]                         Part: :getAddressResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.GetAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}getAddressResponse

[DEBUG]                         Faults:


rejected promise not handled within 1 second

[main 2019-02-20T14:07:52.281Z] update#setState checking for updates

[main 2019-02-20T14:07:52.329Z] update#setState available for download

    1) should be able to run command: extension.wsdl2rest - with local wsdl file


  Wsdl2rest Extension Tests from URL-provided wsdl file

server running on port 3000

Started web service on http://localhost:3000/helloworldservice
    - Should do something with wsdl2rest accessing a wsdl from a running web service



  3 passing (50s)
  1 pending
  1 failing

  1) Wsdl2rest Extension Tests from wsdl file
       should be able to run command: extension.wsdl2rest - with local wsdl file:
     Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  





Tests exited with code: 1
npm ERR! Test failed.  See above for more details.
```

**Comment by bfitzpat** [comment]
Success

```
$ npm test

> vscode-wsdl2rest@0.0.1 test C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> npm run compile && node ./node_modules/vscode/bin/test


> vscode-wsdl2rest@0.0.1 compile C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest
Running extension tests: C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\.vscode-test\stable\Code.exe C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test --extensionDevelopmentPath=C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest --extensionTestsPath=C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test --locale=en


[main 2019-02-20T18:13:17.754Z] update#setState idle

c:\Users\brianf\.vscode\extensions\camel-tooling.vscode-apache-camel-0.0.13\jars\language-server.jar

Rejected cached data from file: C:\Users\brianf\AppData\Roaming\Code\CachedData\7c66f58312b48ed8ca4e387ebd9ffe9605332caa\extension.test-0e5d8bc9b016e18cf180633d1c320a50.code





  ensure Wsdl2rest extension exists and is accessible

    √ Extension should be present

Rejected cached data from file: C:\Users\brianf\AppData\Roaming\Code\CachedData\7c66f58312b48ed8ca4e387ebd9ffe9605332caa\utils-e8786dc4dd0eb7c1894ea7dfa1f6d543.code

Rejected cached data from file: C:\Users\brianf\AppData\Roaming\Code\CachedData\7c66f58312b48ed8ca4e387ebd9ffe9605332caa\extension-bc21f28c7ba96b8c9f905831af0496f1.code
    √ should activate (784ms)

    √ should register all wsdl2rest commands


  Wsdl2rest Extension Tests from wsdl file - spring

addressWsdlPath = C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\src\test\address.wsdl

[DEBUG] WSDL File URI: file:///c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl
[DEBUG] DSL Type: Blueprint
[DEBUG] Ouput Folder: src/main/java
[DEBUG] JAXWS Endpoint: http://localhost:8080/somepath
[DEBUG] JAXRS Endpoint: http://localhost:8081/jaxrs

[DEBUG] New config folder: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\config

[DEBUG] Log4J Config: file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/out/test/config/logging.properties
[DEBUG] Java Binary: C:\Program Files\Java\jdk1.8.0_162\bin\java
[DEBUG] Wsdl2Rest JAR: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\jars\wsdl2rest.jar
[DEBUG] Java Call: C:\Program Files\Java\jdk1.8.0_162\bin\java
        -Dlog4j.configuration=file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/out/test/config/logging.properties,-jar,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\jars\wsdl2rest.jar,--wsdl,file:///c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl,--out,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\src\main,--blueprint-context,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\src\main\resources\OSGI-INF\blueprint\blueprint.xml,--jaxrs,http://localhost:8081/jaxrs,--jaxws,http://localhost:8080/somepath

[DEBUG] Retrieving document at 'file:/c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl'.


[DEBUG] Services:


[DEBUG]         AddressService


[DEBUG]         Port: AddressPort
        Binding: Address
        PortType: Address


[DEBUG]         Operations:

[DEBUG]                 Operation: delAddress


[DEBUG]                         Input:

[DEBUG]                         Message: delAddress

[DEBUG]                         Part: :delAddress

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.DelAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}delAddress

[DEBUG]                         Output:

[DEBUG]                         Message: delAddressResponse

[DEBUG]                         Part: :delAddressResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.DelAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}delAddressResponse
[DEBUG]                         Faults:

[DEBUG]                 Operation: addAddress
                        Input:

[DEBUG]                         Message: addAddress

[DEBUG]                         Part: :addAddress
                                Params: org.jboss.fuse.wsdl2rest.test.doclit.AddAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}addAddress

[DEBUG]                         Output:
                        Message: addAddressResponse

[DEBUG]                         Part: :addAddressResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.AddAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}addAddressResponse
[DEBUG]                         Faults:

[DEBUG]                 Operation: listAddresses
                        Input:

[DEBUG]                         Message: listAddresses
                        Part: :listAddresses

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.ListAddresses {http://doclit.test.wsdl2rest.fuse.jboss.org/}listAddresses

[DEBUG]                         Output:
                        Message: listAddressesResponse

[DEBUG]                         Part: :listAddressesResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.ListAddressesResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}listAddressesResponse

[DEBUG]                         Faults:
                Operation: updAddress

[DEBUG]                         Input:
                        Message: updAddress

[DEBUG]                         Part: :updAddress

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.UpdAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}updAddress

[DEBUG]                         Output:

[DEBUG]                         Message: updAddressResponse
                        Part: :updAddressResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.UpdAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}updAddressResponse
[DEBUG]                         Faults:

[DEBUG]                 Operation: getAddress

[DEBUG]                         Input:

[DEBUG]                         Message: getAddress

[DEBUG]                         Part: :getAddress
                                Params: org.jboss.fuse.wsdl2rest.test.doclit.GetAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}getAddress

[DEBUG]                         Output:
                        Message: getAddressResponse

[DEBUG]                         Part: :getAddressResponse
                                Params: org.jboss.fuse.wsdl2rest.test.doclit.GetAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}getAddressResponse

[DEBUG]                         Faults:


    √ should be able to run command: extension.wsdl2rest - with local wsdl file - spring (3414ms)

addressWsdlPath = C:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\src\test\address.wsdl

[DEBUG] WSDL File URI: file:///c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl
[DEBUG] DSL Type: Blueprint
[DEBUG] Ouput Folder: src/main/java
[DEBUG] JAXWS Endpoint: http://localhost:8080/somepath
[DEBUG] JAXRS Endpoint: http://localhost:8081/jaxrs

[DEBUG] New config folder: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\config

[DEBUG] Log4J Config: file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/out/test/config/logging.properties
[DEBUG] Java Binary: C:\Program Files\Java\jdk1.8.0_162\bin\java
[DEBUG] Wsdl2Rest JAR: c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\jars\wsdl2rest.jar
[DEBUG] Java Call: C:\Program Files\Java\jdk1.8.0_162\bin\java
        -Dlog4j.configuration=file:///c:/Users/brianf/Documents/GitHub/vscode-wsdl2rest/out/test/config/logging.properties,-jar,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\jars\wsdl2rest.jar,--wsdl,file:///c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl,--out,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\src\main,--blueprint-context,c:\Users\brianf\Documents\GitHub\vscode-wsdl2rest\out\test\src\main\resources\OSGI-INF\blueprint\blueprint.xml,--jaxrs,http://localhost:8081/jaxrs,--jaxws,http://localhost:8080/somepath

[DEBUG] Retrieving document at 'file:/c%3A/Users/brianf/Documents/GitHub/vscode-wsdl2rest/src/test/address.wsdl'.

[DEBUG]


[DEBUG] Services:


[DEBUG]         AddressService

[DEBUG]         Port: AddressPort

[DEBUG]         Binding: Address

[DEBUG]         PortType: Address

[DEBUG]         Operations:

[DEBUG]                 Operation: delAddress

[DEBUG]                         Input:

[DEBUG]                         Message: delAddress

[DEBUG]                         Part: :delAddress

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.DelAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}delAddress

[DEBUG]                         Output:

[DEBUG]                         Message: delAddressResponse

[DEBUG]                         Part: :delAddressResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.DelAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}delAddressResponse
[DEBUG]                         Faults:

[DEBUG]                 Operation: addAddress

[DEBUG]                         Input:

[DEBUG]                         Message: addAddress

[DEBUG]                         Part: :addAddress

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.AddAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}addAddress

[DEBUG]                         Output:
                        Message: addAddressResponse

[DEBUG]                         Part: :addAddressResponse
                                Params: org.jboss.fuse.wsdl2rest.test.doclit.AddAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}addAddressResponse

[DEBUG]                         Faults:

[DEBUG]                 Operation: listAddresses
                        Input:
                        Message: listAddresses

[DEBUG]                         Part: :listAddresses
                                Params: org.jboss.fuse.wsdl2rest.test.doclit.ListAddresses {http://doclit.test.wsdl2rest.fuse.jboss.org/}listAddresses

[DEBUG]                         Output:
                        Message: listAddressesResponse

[DEBUG]                         Part: :listAddressesResponse

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.ListAddressesResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}listAddressesResponse

[DEBUG]                         Faults:

[DEBUG]                 Operation: updAddress

[DEBUG]                         Input:

[DEBUG]                         Message: updAddress
                        Part: :updAddress

[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.UpdAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}updAddress

[DEBUG]                         Output:

[DEBUG]                         Message: updAddressResponse


[DEBUG]                         Part: :updAddressResponse


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.UpdAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}updAddressResponse                        Faults:
                Operation: getAddress

[DEBUG]                         Input:


[DEBUG]                         Message: getAddress


[DEBUG]                         Part: :getAddress


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.GetAddress {http://doclit.test.wsdl2rest.fuse.jboss.org/}getAddress


[DEBUG]                         Output:


[DEBUG]                         Message: getAddressResponse


[DEBUG]                         Part: :getAddressResponse


[DEBUG]                                 Params: org.jboss.fuse.wsdl2rest.test.doclit.GetAddressResponse {http://doclit.test.wsdl2rest.fuse.jboss.org/}getAddressResponse

[DEBUG]                         Faults:


    √ should be able to run command: extension.wsdl2rest - with local wsdl file - blueprint (3129ms)



  Wsdl2rest Extension Tests from URL-provided wsdl file
server running on port 3000
Started web service on http://localhost:3000/helloworldservice
    - Should do something with wsdl2rest accessing a wsdl from a running web service


  5 passing (7s)
  1 pending


Tests exited with code: 0
```

**Pull request merged**
